# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["fastly@thatdarnpat.com"]
cloned_from = "https://github.com/fastly/compute-starter-kit-go-default"
description = "Go get 'em, Tiger..."
language = "go"
manifest_version = 3
name = "tiger"
service_id = ""

[scripts]
  build = "go build -o bin/main.wasm ."
  env_vars = ["GOARCH=wasm", "GOOS=wasip1"]
  post_init = "go get github.com/fastly/compute-sdk-go@latest"
